name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build problem.tex
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          working_directory: problem
          root_file: problem.tex
      - name: Build solution.tex
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          working_directory: solution
          root_file: solution.tex
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            problem/problem.pdf
            solution/solution.pdf
          tag_name: ${{ steps.date.outputs.date }}
